StoreApp.WEBUI/Models/ResultMessage.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StoreApp.WEBUI.Models
{
    public class ResultMessage
    {
        public string Title { get; set; }
        public string Message { get; set; }
        public string Css { get; set; }
    }
}

StoreApp.WEBUI/Controllers/CartController.cs
using Iyzipay;
using Iyzipay.Model;
using Iyzipay.Request;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using StoreApp.Business.Abstract;
using StoreApp.Entities;
using StoreApp.WEBUI.Identity;
using StoreApp.WEBUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StoreApp.WEBUI.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private ICartService _cartService;
        private UserManager<ApplicationUser> _userManager;
        private IOrderService _orderService;

        public CartController(ICartService cartService, UserManager<ApplicationUser> userManager, IOrderService orderService)
        {
            _cartService = cartService;
            _userManager = userManager;
            _orderService = orderService;
        }

        public IActionResult Index()
        {
            var cart = _cartService.GetCartByUserID(_userManager.GetUserId(User));
            return View(new CartModel()

            {
                CartId = cart.CartID,
                CartItems = cart.CartItems.Select(i => new CartItemModel()
                {
                    CartItemId = i.CartID,
                    ProductId = i.ProductID,
                    ProductName = i.Product.ProductName,
                    UnitPrice = (decimal)i.Product.UnitPrice,
                    ImageUrl = i.Product.ImageUrl,
                    Quantity = i.Quantity
                }).ToList()
            });
        }

        [HttpPost]
        public IActionResult AddToCart(int productId, int quantity)
        {
            _cartService.AddToCart(_userManager.GetUserId(User), productId, quantity);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult RemoveFromCart(int productId)
        {
            _cartService.RemoveFromCart(_userManager.GetUserId(User), productId);
            return RedirectToAction("Index");
        }

        public IActionResult Checkout()
        {
            var cart = _cartService.GetCartByUserID(_userManager.GetUserId(User));

            var orderModel = new OrderModel();

            orderModel.CartModel = new CartModel()
            {
                CartId = cart.CartID,
                CartItems = cart.CartItems.Select(i => new CartItemModel()
                {
                    CartItemId = i.CartItemID,
                    ProductId = i.ProductID,
                    ProductName = i.Product.ProductName,
                    UnitPrice = (decimal)i.Product.UnitPrice,
                    ImageUrl = i.Product.ImageUrl,
                    Quantity = i.Quantity
                }).ToList()
            };


            return View(orderModel);
        }

        [HttpPost]
        public IActionResult Checkout(OrderModel model)
        {
            if (ModelState.IsValid)
            {
                var userId = _userManager.GetUserId(User);
                var cart = _cartService.GetCartByUserID(userId);

                model.CartModel = new CartModel()
                {
                    CartId = cart.CartID,
                    CartItems = cart.CartItems.Select(i => new CartItemModel()
                    {
                        CartItemId = i.CartID,
                        ProductId = i.ProductID,
                        ProductName = i.Product.ProductName,
                        UnitPrice = (decimal)i.Product.UnitPrice,
                        ImageUrl = i.Product.ImageUrl,
                        Quantity = i.Quantity
                    }).ToList()
                };

                //odeme
                var payment = PaymentProcess(model);

                if (payment.Status == "success")
                {
                    SaveOrder(model, payment, userId);
                    ClearCart(cart.CartID);
                    return View("Success");
                }
                //sipariş
            }
            return View(model);

        }

        private void SaveOrder(OrderModel model, Payment payment, string userId)
        {
            var order = new Order();

            order.OrderNumber = new Random().Next(100000, 999999).ToString();
            order.OrderStatus = EnumOrderStatus.Completed;
            order.PaymentTypes = EnumPaymentTypes.CreditCart;
            order.PaymentID = payment.PaymentId;
            order.ConversationID = payment.ConversationId;
            order.OrderDate = new DateTime();
            order.FirstName = model.FirstName;
            order.LastName = model.LastName;
            order.Email = model.Email;
            order.Phone = model.Phone;
            order.Address = model.Address;
            order.City = model.City;
            order.UserId = userId;

            foreach (var item in model.CartModel.CartItems)
            {
                var orderitem = new Entities.OrderItem()
                {
                    Price = item.UnitPrice,
                    Quantity = item.Quantity,
                    ProductID = item.ProductId
                };
                order.OrderItems.Add(orderitem);
            }
            _orderService.Create(order);
        }

        private void ClearCart(int cartId)
        {
            _cartService.ClearCart(cartId);
        }

        private Payment PaymentProcess(OrderModel model)
        {
            Options options = new Options();
            options.ApiKey = "sandbox-IBWl7atBop2ycillEZDvtaqlfIqr6AOM";
            options.SecretKey = "sandbox-XTMyS8A9xdC63L13pnvbcJMlg6RD73bP";
            options.BaseUrl = "https://sandbox-api.iyzipay.com";



            CreatePaymentRequest request = new CreatePaymentRequest();
            request.Locale = Locale.TR.ToString();
            request.ConversationId = Guid.NewGuid().ToString();
            request.Price = model.CartModel.TotalPrice().ToString().Split(",")[0];
            request.PaidPrice = model.CartModel.TotalPrice().ToString().Split(",")[0];
            request.Currency = Currency.TRY.ToString();
            request.Installment = 1;
            request.BasketId = model.CartModel.CartId.ToString();
            request.PaymentChannel = PaymentChannel.WEB.ToString();
            request.PaymentGroup = PaymentGroup.PRODUCT.ToString();

            PaymentCard paymentCard = new PaymentCard();
            paymentCard.CardHolderName = model.CardName;
            paymentCard.CardNumber = model.CardNumber;
            paymentCard.ExpireMonth = model.ExpirationMonth;
            paymentCard.ExpireYear = model.ExpirationYear;
            paymentCard.Cvc = model.CVV;
            paymentCard.RegisterCard = 0;
            request.PaymentCard = paymentCard;


            Buyer buyer = new Buyer();
            buyer.Id = "BY789";
            buyer.Name = "John";
            buyer.Surname = "Doe";
            buyer.GsmNumber = "+905350000000";
            buyer.Email = "email@email.com";
            buyer.IdentityNumber = "74300864791";
            buyer.LastLoginDate = "2015-10-05 12:43:35";
            buyer.RegistrationDate = "2013-04-21 15:12:09";
            buyer.RegistrationAddress = "Nidakule Göztepe, Merdivenköy Mah. Bora Sok. No:1";
            buyer.Ip = "85.34.78.112";
            buyer.City = "Istanbul";
            buyer.Country = "Turkey";
            buyer.ZipCode = "34732";
            request.Buyer = buyer;

            Address shippingAddress = new Address();
            shippingAddress.ContactName = "Jane Doe";
            shippingAddress.City = "Istanbul";
            shippingAddress.Country = "Turkey";
            shippingAddress.Description = "Nidakule Göztepe, Merdivenköy Mah. Bora Sok. No:1";
            shippingAddress.ZipCode = "34742";
            request.ShippingAddress = shippingAddress;

            Address billingAddress = new Address();
            billingAddress.ContactName = "Jane Doe";
            billingAddress.City = "Istanbul";
            billingAddress.Country = "Turkey";
            billingAddress.Description = "Nidakule Göztepe, Merdivenköy Mah. Bora Sok. No:1";
            billingAddress.ZipCode = "34742";
            request.BillingAddress = billingAddress;

            List<BasketItem> basketItems = new List<BasketItem>();
            BasketItem basketItem;

            foreach (var item in model.CartModel.CartItems)
            {
                basketItem = new BasketItem();
                basketItem.Id = item.ProductId.ToString();
                basketItem.Name = item.ProductName;
                basketItem.ItemType = BasketItemType.PHYSICAL.ToString();
                basketItem.Category1 = "KategoriyiAtBuraya";
                basketItem.Price = (item.UnitPrice*item.Quantity).ToString().Split(",")[0];
                basketItems.Add(basketItem);
            }


            request.BasketItems = basketItems;


            return Payment.Create(request, options);


        }

        public IActionResult GetOrders()
        {
            var orders = _orderService.GetOrders(_userManager.GetUserId(User));

            var orderListModel = new List<OrderListModel>();

            OrderListModel orderModel;

            foreach (var order in orders)
            {
                orderModel = new OrderListModel();
                orderModel.OrderID = order.OrderID;
                orderModel.OrderNumber = order.OrderNumber;
                orderModel.OrderDate = order.OrderDate;
                orderModel.OrderNote = order.OrderNote;
                orderModel.OrderStatus = order.OrderStatus;
                orderModel.FirstName = order.FirstName;
                orderModel.LastName = order.LastName;
                orderModel.Email = order.Email;
                orderModel.Phone = order.Phone;
                orderModel.City = order.City;
                orderModel.Address = order.Address;

                orderModel.OrderItems = order.OrderItems.Select(i => new OrderItemModel()

StoreApp.WEBUI/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using StoreApp.Business.Abstract;
using StoreApp.Entities;
using StoreApp.WEBUI.Identity;
using StoreApp.WEBUI.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace StoreApp.WEBUI.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private IProductService _productservice;
        private ICategorySubService _categorySubService;
        private ICategoryService _categoryService;
        private UserManager<ApplicationUser> _userManager;


        public UserController(UserManager<ApplicationUser> userManager,IProductService productservice, ICategorySubService categorySubService, ICategoryService categoryService)
        {
            _productservice = productservice;
            _categorySubService = categorySubService;
            _categoryService = categoryService;
            _userManager = userManager;
        }
        //public IActionResult ProductList()
        //{
        //    return View(new ProductListModel()
        //    {
        //        Products = _productservice.GetAll()
        //    });
        //}
        
        [HttpGet]
        public IActionResult CreateProduct()
        {
            return View(new ProductModel());
        }

        [HttpPost]
        public async Task<IActionResult> CreateProduct(ProductModel model, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                var userId = _userManager.GetUserId(User);

                var entity = new Product()
                {
                    ProductName = model.ProductName,
                    Description = model.Description,
                    UnitPrice = model.UnitPrice,
                    DisplayDate = DateTime.Now,
                    UserId = userId
                };

                if (file != null)
                {
                    entity.ImageUrl = file.FileName;

                    var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images\\products", (file.FileName));
                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        await file.CopyToAsync(stream);
                    }
                }


                _productservice.Create(entity);

                return RedirectToAction("MyProducts");


            }

            return View(model);


        }


        public IActionResult EditProduct(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var entity = _productservice.GetByIDWithCategorySubs((int)id);


            if (entity == null)
            {
                return NotFound();
            }

            var model = new ProductModel()
            {
                ProductID = entity.ProductID,
                ProductName = entity.ProductName,
                UnitPrice = entity.UnitPrice,
                ImageUrl = entity.ImageUrl,
                Description = entity.Description,
                Categories = _categoryService.GetAll(),
                SelectedCategorySubs = entity.ProductCategorySubs.Select(i => i.CategorySub).ToList(),

            };

            ViewBag.CategorySubs = _categorySubService.GetAll();

            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> EditProduct(ProductModel model, int[] categorySubIDs, IFormFile file)
        {
            if (ModelState.IsValid)
            {


                var entity = _productservice.GetByID(model.ProductID);
                if (entity == null)
                {
                    return NotFound();
                }
                entity.ProductName = model.ProductName;
                entity.Description = model.Description;
                entity.UnitPrice = model.UnitPrice;

                if (file != null)
                {
                    entity.ImageUrl = file.FileName;

                    var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images\\products", (file.FileName));
                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        await file.CopyToAsync(stream);
                    }
                }
                _productservice.Update(entity, categorySubIDs);

                return RedirectToAction("MyProducts");
            }
            return View(model);
        }

        [HttpPost]
        public IActionResult DeleteProduct(int productID)
        {
            var entity = _productservice.GetByID(productID);
            if (entity != null)
            {
                _productservice.Delete(entity);
            }
            return RedirectToAction("MyProducts");
        }

        public JsonResult BringCategorySubs(int id)
        {
            var model = new ProductModel()
            {
                SelectedCategoryWithCategorySubs = _categorySubService.GetAll()
            };
            return Json(model);
        }

        public IActionResult MyProducts()
        {
            var products = _productservice.GetProducts(_userManager.GetUserId(User));

            var productListModel = new List<ProductModel>();

            ProductModel productModel;

            foreach (var product in products)
            {
                productModel = new ProductModel();
                productModel.ProductID = product.ProductID;
                productModel.ProductName = product.ProductName;
                productModel.ImageUrl = product.ImageUrl;
                productModel.DisplayDate = product.DisplayDate;
                productModel.Description = product.Description;
                productModel.UnitPrice = product.UnitPrice;
                productModel.UnitsInOrder = product.UnitsInOrder;
                productModel.UnitsInStock = product.UnitsInStock;

                productListModel.Add(productModel);

            }


            return View(productListModel);
        }





    }
}

StoreApp.WEBUI/Views/Shared/_Advertised.cshtml
@model Advertised

<div class="col-md-4 top_brand_left" style="margin-bottom:10px">
    <div class="hover14 column">
        <div class="agile_top_brand_left_grid">
            <div class="agile_top_brand_left_grid_pos">
                <img src="~/images/offer.png" alt=" " class="img-responsive" />
            </div>
            <div class="agile_top_brand_left_grid1">
                <figure>
                    <div class="snipcart-item block">
                        <div class="snipcart-thumb">
                            <a asp-controller="Store" asp-action="Details" asp-route-id="@Model.Product.ProductID">
                                <img title=" " alt=" " src="~/images/products/@Model.Product.ImageUrl" width="150" height="150" />
                                <p>@Model.Product.ProductName</p>
                            </a>
                        <h4>@Model.Product.UnitPrice ₺</h4>
                        </div>
                        <div class="snipcart-details top_brand_home_details">
                            <form asp-controller="Cart" asp-action="AddToCart" method="post">
                                <fieldset>

                                    @if (User.Identity.IsAuthenticated)
                                    {

                                        <input type="hidden" name="productId" value="@Model.ProductID" />
                                        <input type="hidden" name="quantity" value="1" />


                                        <input type="submit" value="Sepete Ekle" class="button">
                                    }
                                </fieldset>
                            </form>
                        </div>
                    </div>
                </figure>
            </div>
        </div>
    </div>
</div>

StoreApp.WEBUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Super Market an Ecommerce Online Shopping Category Flat Bootstrap Responsive Website Template | Home :: w3layouts</title>
    <!-- for-mobile-apps -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Super Market Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
    <script type="application/x-javascript">
        addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
               function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!-- //for-mobile-apps -->
    <link href="~/css/bootstrap.css" rel="stylesheet" type="text/css" media="all" />
    <link href="~/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <!-- font-awesome icons -->
    <link href="~/css/font-awesome.css" rel="stylesheet">
    <!-- //font-awesome icons -->
    <!-- js -->
    <script src="~/js/jquery-1.11.1.min.js"></script>
    <!-- //js -->
    <link href='//fonts.googleapis.com/css?family=Raleway:400,100,100italic,200,200italic,300,400italic,500,500italic,600,600italic,700,700italic,800,800italic,900,900italic' rel='stylesheet' type='text/css'>
    <link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
    <!-- start-smoth-scrolling -->
    <script type="text/javascript" src="~/js/move-top.js"></script>
    <script type="text/javascript" src="~/js/easing.js"></script>
    <script type="text/javascript">
        jQuery(document).ready(function ($) {
            $(".scroll").click(function (event) {
                event.preventDefault();
                $('html,body').animate({ scrollTop: $(this.hash).offset().top }, 1000);
            });
        });
    </script>
    <!-- start-smoth-scrolling -->
</head>
<body>
    <!-- header -->
    <div class="agileits_header">
        <div class="container" style="display:flex; flex-direction:row; justify-content:space-between;">
            <div class="w3l_offers">
                <p> <a asp-controller="Store" asp-action="Products">Şimdi Satın Al</a></p>
            </div>
            <div class="agile-login" style="display:flex; flex-direction:row; justify-content:space-between;">
                <ul>
                    @if (User.Identity.IsAuthenticated)
                    {

                        <li><a asp-controller="User" asp-action="MyProducts"> Ürünlerim </a></li>
                        <li><a asp-controller="User" asp-action="CreateProduct"> Ürün Ekle </a></li>
                        <li><a asp-controller="Cart" asp-action="GetOrders"> Siparişlerim </a></li>
                        @if (User.IsInRole("Admin"))
                        {
                            @*<li><a asp-controller="Admin" asp-action="ProductList"> Ürünler </a></li>*@
                            <li><a asp-controller="Admin" asp-action="CategoryList">Kategoriler </a></li>
                            <li><a asp-controller="Admin" asp-action="CreateCategory"> Kategori Ekle </a></li>
                            <li><a asp-controller="Admin" asp-action="CategorySubList">Alt Kategoriler </a></li>
                            <li><a asp-controller="Admin" asp-action="CreateCategorySub">Alt Kategori Ekle </a></li>
                        }

                    }
                    else
                    {

                    }



                    @if (User.Identity.IsAuthenticated)
                    {
                        @*<li><a asp-controller="Account" asp-action="Manage" style="text-transform:none">@User.Identity.Name </a></li>*@
                        <li><a asp-controller="Account" asp-action="Logout">Çıkış Yap </a></li>
                    }
                    else
                    {
                        <li><a asp-controller="Account" asp-action="Register">Kayıt Ol </a></li>
                        <li><a asp-controller="Account" asp-action="Login">Giriş Yap </a></li>
                    }




                </ul>
            </div>
            <!--sepet sembol-->




            <div class="product_list_header" style="display:flex; flex-direction:row; justify-content:space-between;">
                <form asp-controller="Favorite" asp-action="Index" method="get" class="last">
                    <button class="w3view-cart" value=""><i class="fa fa-heart-o" aria-hidden="true"></i></button>
                </form>
                <form asp-controller="Cart" asp-action="Index" method="get" class="last">
                    <button class="w3view-cart" value=""><i class="fa fa-cart-arrow-down" aria-hidden="true"></i></button>
                </form>
            </div>
            <div class="clearfix"> </div>
        </div>
    </div>

    <div class="logo_products">
        <div class="container">
            <div class="w3ls_logo_products_left1">
                <ul class="phone_email">
                    <li><i class="fa fa-phone" aria-hidden="true"></i>Müşteri Hizmetleri : (+0123) 234 56 78</li>

                </ul>
            </div>
            <div class="w3ls_logo_products_left">
                <h1><a asp-controller="Home" asp-action="Index">Benim Mağazam</a></h1>
            </div>
            <div class="w3l_search">
                <form asp-controller="Store" asp-action="Products" method="get">
                    <input type="search" name="searchString" placeholder="Ürün Ara" required="">
                    <button type="submit" class="btn btn-default search" aria-label="Left Align">
                        <i class="fa fa-search" aria-hidden="true"> </i>
                    </button>
                    <div class="clearfix"></div>
                </form>
            </div>

            <div class="clearfix"> </div>
        </div>
    </div>

    <!-- //header -->
    <!-- navigation -->

    @await Component.InvokeAsync("CategoryNavbarList")

    <!-- //navigation -->
    @if (TempData["message"] != null)
    {
        <partial name="_ResultMessage" model="@(TempData.Get<ResultMessage>("message"))" />
    }


    @RenderBody()


    <!-- //footer -->
    <div class="footer">
        <div class="container">
            <div class="w3_footer_grids">
                <div class="col-md-3 w3_footer_grid">
                    <h3>Contact</h3>

                    <ul class="address">
                        <li><i class="glyphicon glyphicon-map-marker" aria-hidden="true"></i>1234k Avenue, 4th block, <span>New York City.</span></li>
                        <li><i class="glyphicon glyphicon-envelope" aria-hidden="true"></i><a href="mailto:info@example.com">info@example.com</a></li>
                        <li><i class="glyphicon glyphicon-earphone" aria-hidden="true"></i>+1234 567 567</li>
                    </ul>
                </div>
                <div class="col-md-3 w3_footer_grid">
                    <h3>Information</h3>
                    <ul class="info">
                        <li><i class="fa fa-arrow-right" aria-hidden="true"></i><a href="about.html">About Us</a></li>
                        <li><i class="fa fa-arrow-right" aria-hidden="true"></i><a href="contact.html">Contact Us</a></li>
                        <li><i class="fa fa-arrow-right" aria-hidden="true"></i><a href="short-codes.html">Short Codes</a></li>
                        <li><i class="fa fa-arrow-right" aria-hidden="true"></i><a href="faq.html">FAQ's</a></li>
                        <li><i class="fa fa-arrow-right" aria-hidden="true"></i><a href="products.html">Special Products</a></li>
                    </ul>
                </div>
                <div class="col-md-3 w3_footer_grid">
                    <h3>Category</h3>
                    <ul class="info">
                        <li><i class="fa fa-arrow-right" aria-hidden="true"></i><a href="groceries.html">Groceries</a></li>
                        <li><i class="fa fa-arrow-right" aria-hidden="true"></i><a href="household.html">Household</a></li>
                        <li><i class="fa fa-arrow-right" aria-hidden="true"></i><a href="personalcare.html">Personal Care</a></li>
                        <li><i class="fa fa-arrow-right" aria-hidden="true"></i><a href="packagedfoods.html">Packaged Foods</a></li>
                        <li><i class="fa fa-arrow-right" aria-hidden="true"></i><a href="beverages.html">Beverages</a></li>
                    </ul>
                </div>
                <div class="col-md-3 w3_footer_grid">
                    <h3>Profile</h3>
                    <ul class="info">
                        <li><i class="fa fa-arrow-right" aria-hidden="true"></i><a href="products.html">Store</a></li>
                        <li><i class="fa fa-arrow-right" aria-hidden="true"></i><a href="checkout.html">My Cart</a></li>
                        <li><i class="fa fa-arrow-right" aria-hidden="true"></i><a href="login.html">Login</a></li>
                        <li><i class="fa fa-arrow-right" aria-hidden="true"></i><a href="registered.html">Create Account</a></li>
                    </ul>
                </div>
                <div class="clearfix"> </div>
            </div>
        </div>

        <div class="footer-copy">

            <div class="container">
                <p>© 2017 Super Market. All rights reserved | Design by <a href="http://w3layouts.com/">W3layouts</a></p>
            </div>
        </div>

    </div>
    <div class="footer-botm">
        <div class="container">
            <div class="w3layouts-foot">
                <ul>
                    <li><a href="#" class="w3_agile_facebook"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                    <li><a href="#" class="agile_twitter"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                    <li><a href="#" class="w3_agile_dribble"><i class="fa fa-dribbble" aria-hidden="true"></i></a></li>
                    <li><a href="#" class="w3_agile_vimeo"><i class="fa fa-vimeo" aria-hidden="true"></i></a></li>
                </ul>
            </div>
            <div class="payment-w3ls">
                <img src="~/images/card.png" alt=" " class="img-responsive">
            </div>
            <div class="clearfix"> </div>
        </div>
    </div>
    <!-- Bootstrap Core JavaScript -->
    <script src="~/js/bootstrap.min.js"></script>

    <!-- top-header and slider -->
    <!-- here stars scrolling icon -->
    <script type="text/javascript">
        $(document).ready(function () {
            /*
                var defaults = {
                containerID: 'toTop', // fading element id
                containerHoverID: 'toTopHover', // fading element hover id
                scrollSpeed: 1200,
                easingType: 'linear'
                };
            */

            $().UItoTop({ easingType: 'easeOutQuart' });

        });
    </script>
    <!-- //here ends scrolling icon -->
    <script src="~/js/minicart.min.js"></script>
    <script>
        // Mini Cart
        paypal.minicart.render({
            action: '#'
        });

        if (~window.location.search.indexOf('reset=true')) {
            paypal.minicart.reset();
        }
    </script>

    @RenderSection("Scripts", required: false)
</body>
</html>

StoreApp.WEBUI/Views/Shared/_Product.cshtml
@model Product
<div class="col-md-4 top_brand_left " style="margin-bottom:10px;">
    <div class="hover14 column">
        <div class="agile_top_brand_left_grid">
            <div class="agile_top_brand_left_grid_pos">
                <img src="~/images/offer.png" alt=" " class="img-responsive">
            </div>
            <div class="agile_top_brand_left_grid1">
                <figure>
                    <div class="snipcart-item block">
                        <div class="snipcart-thumb">
                            <a asp-controller="Store" asp-action="Details" asp-route-id="@Model.ProductID">
                                <img title=" " alt=" " src="~/images/products/@Model.ImageUrl" width="150" height="150">
                                <p>@Model.ProductName</p>
                            </a>
                            <h4>@Model.UnitPrice ₺ @*<span>$55.00</span>*@</h4>
                        </div>
                        <div class="snipcart-details top_brand_home_details">
                            <form asp-controller="Cart" asp-action="AddToCart" method="post">
                                <fieldset>

                                    @if (User.Identity.IsAuthenticated)
                                    {

                                        <input type="hidden" name="productId" value="@Model.ProductID" />
                                        <input type="hidden" name="quantity" value="1" />


                                        <input type="submit" value="Sepete Ekle" class="button">
                                    }
                                </fieldset>
                            </form>
                        </div>
                    </div>
                </figure>
            </div>
        </div>
    </div>
</div>