StoreApp.WEBUI/Controllers/CartController.cs
using Iyzipay;
using Iyzipay.Model;
using Iyzipay.Request;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using StoreApp.Business.Abstract;
using StoreApp.Entities;
using StoreApp.WEBUI.Identity;
using StoreApp.WEBUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StoreApp.WEBUI.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private ICartService _cartService;
        private UserManager<ApplicationUser> _userManager;
        private IOrderService _orderService;

        public CartController(ICartService cartService, UserManager<ApplicationUser> userManager, IOrderService orderService)
        {
            _cartService = cartService;
            _userManager = userManager;
            _orderService = orderService;
        }

        public IActionResult Index()
        {
            var cart = _cartService.GetCartByUserID(_userManager.GetUserId(User));
            return View(new CartModel()

            {
                CartId = cart.CartID,
                CartItems = cart.CartItems.Select(i => new CartItemModel()
                {
                    CartItemId = i.CartID,
                    ProductId = i.ProductID,
                    ProductName = i.Product.ProductName,
                    UnitPrice = (decimal)i.Product.UnitPrice,
                    ImageUrl = i.Product.ImageUrl,
                    Quantity = i.Quantity
                }).ToList()
            });
        }

        [HttpPost]
        public IActionResult AddToCart(int productId, int quantity)
        {
            _cartService.AddToCart(_userManager.GetUserId(User), productId, quantity);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult RemoveFromCart(int productId)
        {
            _cartService.RemoveFromCart(_userManager.GetUserId(User), productId);
            return RedirectToAction("Index");
        }

        public IActionResult Checkout()
        {
            var cart = _cartService.GetCartByUserID(_userManager.GetUserId(User));

            var orderModel = new OrderModel();

            orderModel.CartModel = new CartModel()
            {
                CartId = cart.CartID,
                CartItems = cart.CartItems.Select(i => new CartItemModel()
                {
                    CartItemId = i.CartItemID,
                    ProductId = i.ProductID,
                    ProductName = i.Product.ProductName,
                    UnitPrice = (decimal)i.Product.UnitPrice,
                    ImageUrl = i.Product.ImageUrl,
                    Quantity = i.Quantity
                }).ToList()
            };


            return View(orderModel);
        }

        [HttpPost]
        public IActionResult Checkout(OrderModel model)
        {
            if (ModelState.IsValid)
            {
                var userId = _userManager.GetUserId(User);
                var cart = _cartService.GetCartByUserID(userId);

                model.CartModel = new CartModel()
                {
                    CartId = cart.CartID,
                    CartItems = cart.CartItems.Select(i => new CartItemModel()
                    {
                        CartItemId = i.CartID,
                        ProductId = i.ProductID,
                        ProductName = i.Product.ProductName,
                        UnitPrice = (decimal)i.Product.UnitPrice,
                        ImageUrl = i.Product.ImageUrl,
                        Quantity = i.Quantity
                    }).ToList()
                };

                //odeme
                var payment = PaymentProcess(model);

                if (payment.Status == "success")
                {
                    SaveOrder(model, payment, userId);
                    ClearCart(cart.CartID);
                    return View("Success");
                }
                //sipariş
            }
            return View(model);

        }

        private void SaveOrder(OrderModel model, Payment payment, string userId)
        {
            var order = new Order();

            order.OrderNumber = new Random().Next(100000, 999999).ToString();
            order.OrderStatus = EnumOrderStatus.Completed;
            order.PaymentTypes = EnumPaymentTypes.CreditCart;
            order.PaymentID = payment.PaymentId;
            order.ConversationID = payment.ConversationId;
            order.OrderDate = new DateTime();
            order.FirstName = model.FirstName;
            order.LastName = model.LastName;
            order.Email = model.Email;
            order.Phone = model.Phone;
            order.Address = model.Address;
            order.City = model.City;
            order.UserId = userId;

            foreach (var item in model.CartModel.CartItems)
            {
                var orderitem = new Entities.OrderItem()
                {
                    Price = item.UnitPrice,
                    Quantity = item.Quantity,
                    ProductID = item.ProductId
                };
                order.OrderItems.Add(orderitem);
            }
            _orderService.Create(order);
        }

        private void ClearCart(int cartId)
        {
            _cartService.ClearCart(cartId);
        }

        private Payment PaymentProcess(OrderModel model)
        {
            Options options = new Options();
            options.ApiKey = "sandbox-IBWl7atBop2ycillEZDvtaqlfIqr6AOM";
            options.SecretKey = "sandbox-XTMyS8A9xdC63L13pnvbcJMlg6RD73bP";
            options.BaseUrl = "https://sandbox-api.iyzipay.com";



            CreatePaymentRequest request = new CreatePaymentRequest();
            request.Locale = Locale.TR.ToString();
            request.ConversationId = Guid.NewGuid().ToString();
            request.Price = model.CartModel.TotalPrice().ToString().Split(",")[0];
            request.PaidPrice = model.CartModel.TotalPrice().ToString().Split(",")[0];
            request.Currency = Currency.TRY.ToString();
            request.Installment = 1;
            request.BasketId = model.CartModel.CartId.ToString();
            request.PaymentChannel = PaymentChannel.WEB.ToString();
            request.PaymentGroup = PaymentGroup.PRODUCT.ToString();

            PaymentCard paymentCard = new PaymentCard();
            paymentCard.CardHolderName = model.CardName;
            paymentCard.CardNumber = model.CardNumber;
            paymentCard.ExpireMonth = model.ExpirationMonth;
            paymentCard.ExpireYear = model.ExpirationYear;
            paymentCard.Cvc = model.CVV;
            paymentCard.RegisterCard = 0;
            request.PaymentCard = paymentCard;


            Buyer buyer = new Buyer();
            buyer.Id = "BY789";
            buyer.Name = "John";
            buyer.Surname = "Doe";
            buyer.GsmNumber = "+905350000000";
            buyer.Email = "email@email.com";
            buyer.IdentityNumber = "74300864791";
            buyer.LastLoginDate = "2015-10-05 12:43:35";
            buyer.RegistrationDate = "2013-04-21 15:12:09";
            buyer.RegistrationAddress = "Nidakule Göztepe, Merdivenköy Mah. Bora Sok. No:1";
            buyer.Ip = "85.34.78.112";
            buyer.City = "Istanbul";
            buyer.Country = "Turkey";
            buyer.ZipCode = "34732";
            request.Buyer = buyer;

            Address shippingAddress = new Address();
            shippingAddress.ContactName = "Jane Doe";
            shippingAddress.City = "Istanbul";
            shippingAddress.Country = "Turkey";
            shippingAddress.Description = "Nidakule Göztepe, Merdivenköy Mah. Bora Sok. No:1";
            shippingAddress.ZipCode = "34742";
            request.ShippingAddress = shippingAddress;

            Address billingAddress = new Address();
            billingAddress.ContactName = "Jane Doe";
            billingAddress.City = "Istanbul";
            billingAddress.Country = "Turkey";
            billingAddress.Description = "Nidakule Göztepe, Merdivenköy Mah. Bora Sok. No:1";
            billingAddress.ZipCode = "34742";
            request.BillingAddress = billingAddress;

            List<BasketItem> basketItems = new List<BasketItem>();
            BasketItem basketItem;

            foreach (var item in model.CartModel.CartItems)
            {
                basketItem = new BasketItem();
                basketItem.Id = item.ProductId.ToString();
                basketItem.Name = item.ProductName;
                basketItem.ItemType = BasketItemType.PHYSICAL.ToString();
                basketItem.Category1 = "KategoriyiAtBuraya";
                basketItem.Price = (item.UnitPrice*item.Quantity).ToString().Split(",")[0];
                basketItems.Add(basketItem);
            }


            request.BasketItems = basketItems;


            return Payment.Create(request, options);


        }

        public IActionResult GetOrders()
        {
            var orders = _orderService.GetOrders(_userManager.GetUserId(User));

            var orderListModel = new List<OrderListModel>();

            OrderListModel orderModel;

            foreach (var order in orders)
            {
                orderModel = new OrderListModel();
                orderModel.OrderID = order.OrderID;
                orderModel.OrderNumber = order.OrderNumber;
                orderModel.OrderDate = order.OrderDate;
                orderModel.OrderNote = order.OrderNote;
                orderModel.OrderStatus = order.OrderStatus;
                orderModel.FirstName = order.FirstName;
                orderModel.LastName = order.LastName;
                orderModel.Email = order.Email;
                orderModel.Phone = order.Phone;
                orderModel.City = order.City;
                orderModel.Address = order.Address;

                orderModel.OrderItems = order.OrderItems.Select(i => new OrderItemModel()

StoreApp.WEBUI/Controllers/FavoriteController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using StoreApp.Business.Abstract;
using StoreApp.WEBUI.Identity;
using StoreApp.WEBUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StoreApp.WEBUI.Controllers
{
    [Authorize]
    public class FavoriteController : Controller
    {
        private IFavoriteService _favoriteService;
        private UserManager<ApplicationUser> _userManager;

        public FavoriteController(IFavoriteService favoriteService, UserManager<ApplicationUser> userManager)
        {
            _favoriteService = favoriteService;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            var favorite = _favoriteService.GetFavoriteByUserID(_userManager.GetUserId(User));
            return View(new FavoriteModel()
            {
                FavoriteId = favorite.FavoriteID,
                FavoriteItems = favorite.FavoriteItems.Select(i => new FavoriteItemModel()
                {
                    FavoriteItemId = i.FavoriteID,
                    ProductId = i.ProductID,
                    ProductName = i.Product.ProductName,
                    UnitPrice = (decimal)i.Product.UnitPrice,
                    ImageUrl = i.Product.ImageUrl
                }).ToList()
            });
        }

        [HttpPost]
        public IActionResult AddToFavorite(int productId)
        {
            _favoriteService.AddToFavorite(_userManager.GetUserId(User), productId);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult RemoveFromFavorite(int productId)
        {
            _favoriteService.RemoveFromFavorite(_userManager.GetUserId(User), productId);
            return RedirectToAction("Index");
        }
    }
}

StoreApp.WEBUI/Controllers/StoreController.cs
using Microsoft.AspNetCore.Mvc;
using StoreApp.Business.Abstract;
using StoreApp.Entities;
using StoreApp.WEBUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StoreApp.WEBUI.Controllers
{
    public class StoreController : Controller
    {
        private IProductService _productService;
        public StoreController(IProductService productService)
        {
            _productService = productService;
        }
        public IActionResult Details(int? id)
        {
            if (id==null)
            {
                return NotFound();
            }
            Product product = _productService.GetProductDetails((int)id);
            if (product==null)
            {
                return NotFound();
            }
            return View(new ProductDetailsModel()
            {
                Product = product,
                CategorySubs = product.ProductCategorySubs.Select(i => i.CategorySub).ToList()
            }) ;
        }

        public IActionResult Products(string searchString,string categorysub, int page=1)
        {
            const int pageSize = 9;
            return View(new ProductListModel()
            {
                PageInfo= new PageInfo()
                {
                    TotalItems= _productService.GetCountByCategorySub(categorysub,searchString),
                    CurrentPage=page,
                    ItemsPerPage=pageSize,
                    CurrentCategorySub=categorysub,
                    SearchText=searchString
                },
                Products = _productService.GetProductsByCategorySub(categorysub,page,pageSize,searchString)
            }) ;
        }
    }
}

StoreApp.WEBUI/Views/Favorite/Index.cshtml
@model FavoriteModel
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (@Model.FavoriteItems.Count>0)
{
<div class="products">
    <div class="container">
        <div class="col-md-12 products-left">
            <div class="agile_top_brands_grids">
                @foreach (var item in Model.FavoriteItems)
                {
                    <div class="col-md-4 top_brand_left">
                        <div class="hover14 column">
                            <div class="agile_top_brand_left_grid">
                                <div class="agile_top_brand_left_grid_pos">
                                    <img src="~/images/offer.png" alt=" " class="img-responsive">
                                </div>
                                <div class="agile_top_brand_left_grid1">
                                    <figure>
                                        <div class="snipcart-item block">
                                            <div class="snipcart-thumb">
                                                <a asp-controller="Store" asp-action="Details" asp-route-id="@item.ProductId">
                                                    <img title=" " alt=" " src="~/images/products/@item.ImageUrl" width="150" height="150">
                                                    <p>@item.ProductName</p>
                                                </a>
                                                <h4>@item.UnitPrice</h4>
                                            </div>
                                            <div class="snipcart-details top_brand_home_details">

                                                <form asp-controller="Cart" asp-action="AddToFavorite" method="post">
                                                    <fieldset>

                                                        @if (User.Identity.IsAuthenticated)
                                                        {

                                                            <input type="hidden" name="productId" value="@item.ProductId" />



                                                            <input type="submit" value="Sepete Ekle" class="button">
                                                        }
                                                    </fieldset>
                                                </form>
                                            </div>

                                            <div class="snipcart-details top_brand_home_details">
                                                <form asp-controller="Favorite" asp-action="RemoveFromFavorite" method="post" style="margin-top:5px">
                                                    <fieldset>

                                                        @if (User.Identity.IsAuthenticated)
                                                        {


                                                            <input type="hidden" name="productId" value="@item.ProductId" />
                                                            <button type="submit" class="button btn-danger">X</button>

                                                        }
                                                    </fieldset>
                                                </form>

                                            </div>
                                        </div>
                                    </figure>
                                </div>
                            </div>
                        </div>
                    </div>
                }

            </div>
        </div>
    </div>
</div>
}

else
{
<div class="alert alert-warning" style="height:500px">
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <h4 style="text-align:center">Henüz favorilerinde hiç bir ürün yok!</h4>
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
</div>
}